-- Keymaps
vim.keymap.set('n', '<Leader>I', ':PackerSync<CR>')
vim.keymap.set('n', '<Leader>wq', ':wq<CR>')
vim.keymap.set('n', '<Leader>w', ':w<CR>')
vim.keymap.set('n', '<Leader>q!', ':q!<CR>')
vim.keymap.set('n', '<Leader>q', ':q<CR>')
vim.keymap.set('n', '<Leader>r', ':so %<CR>')
vim.keymap.set('n', '<Leader>c', ':bd %<CR>')
vim.keymap.set('n', '<Leader>n', ':bdnext %<CR>')
vim.keymap.set('n', '<space>', 'za')
vim.keymap.set('n', '<C-j>', ':m .+1<CR>')
vim.keymap.set('n', '<C-k>', ':m .-2<CR>')
vim.keymap.set('i', '<C-j>', ':m .+1<CR>==gi')
vim.keymap.set('i', '<C-k>', ':m .-2<CR>==gi')
vim.keymap.set('v', '<C-j>', ":m '>+1<CR>gv=gv")
vim.keymap.set('v', '<C-k>', ":m '<-2<CR>gv=gv")
vim.keymap.set('i', 'jj', '<esc>')
vim.keymap.set('i', 'kk', '<esc>')
vim.keymap.set('n', 'j', 'gj')
vim.keymap.set('n', 'k', 'gk')
vim.keymap.set('n', '<CR>', ':noh<CR><CR>')
vim.keymap.set('n', 'vv', '<C-w>v')
vim.keymap.set('n', 'hh', '<C-w>s')
vim.keymap.set('n', 'B', '^')
vim.keymap.set('n', 'E', '$')
vim.keymap.set('n', 'gd', ':lua vim.lsp.buf.definition()<CR>')
vim.keymap.set('n', 'K', ':lua vim.lsp.buf.hover()<CR>')
