tap "burnsra/tap"
tap "go-task/tap"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
tap "homebrew/cask-fonts"

brew "bat"
brew "glib"
brew "coreutils"
brew "cask"
brew "exa"
brew "fzf"
brew "gh"
brew "gnupg"
brew "neovim", args: ["HEAD"]
brew "nmap"
brew "node"
brew "the_silver_searcher"
brew "tmux"
brew "tree"
brew "starship"

cask "meetingbar"
cask "raycast"
cask "iterm"
cask "flux"
cask "dozer"
cask "visual-studio-code-insiders"
cask "font-jetbrains-mono"
