tap "burnsra/tap"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
tap "homebrew/cask-fonts"

brew "cask"
brew "htop"
brew "curl"
brew "bat"
brew "tree"
brew "exa"
brew "fzf"
brew "gh"
brew "gnupg"
brew "neovim", args: ["HEAD"]
brew "nmap"
brew "the_silver_searcher"

cask "obsidian"
cask "meetingbar"
cask "raycast"
cask "kitty"
cask "flux"
cask "dozer"
cask "visual-studio-code-insiders"
cask "karabiner-elements"
cask "appcleaner"
cask "the-unarchiver"
