disableStartupPopups: true
gui:
  showBottomLine: false
customCommands:
  - key: "C"
    command: git commit
    context: "global"
    output: terminal
  - key: "P"
    command: git push
    context: "global"
    output: terminal
