disableStartupPopups: true
gui:
  showBottomLine: false
customCommands:
  - key: "C"
    command: git commit
    context: "global"
    subprocess: true
  - key: "P"
    command: git push
    context: "global"
    subprocess: true
