[window]
padding = { x = 10, y = 10 }
decorations = "ButtonLess"

[font]
normal = { family = "JetBrainsMono Nerd Font" }
bold = { family = "JetBrainsMono Nerd Font" }
italic = {family = "JetBrainsMono Nerd Font" }
bold_italic = { family = "JetBrainsMono Nerd Font" }
size = 18

[cursor]
style = { shape = "Underline", blinking = "Off" }

[mouse]
hide_when_typing = true
